Repository cloud-native-toolkit/image-cli-tools, pull requests merged in 2022-08, with the labels that each got.

#74 Fix permissions for IBM cloud cli plugin directory
  Dockerfile-alpine
  Dockerfile-fedora
Labels: bug, patch

#76 Updates base image to v1.4.0
  .github/workflows/docker-build.yaml
  Containerfile
  Containerfile-alpine
  Containerfile-fedora
  Dockerfile
Labels: minor, feature

#77 Updates base to v1.4.1
  Containerfile-alpine
  Containerfile-fedora
Labels: bug, patch

#78 Updates base image to v1.4.2
  .github/workflows/docker-build.yaml
  .github/workflows/update-base-image.yaml
  Containerfile-alpine
  Containerfile-fedora
Labels: patch, chore

#79 Updates cloud-native-toolkit/image-cli-tools-core module to v1.4.3
  Containerfile-alpine
  Containerfile-fedora
Labels: bug, patch

#80 Updates cloud-native-toolkit/image-cli-tools-core module to v1.4.4
  Containerfile-alpine
  Containerfile-fedora
Labels: bug, patch

#81 Updates cloud-native-toolkit/image-cli-tools-core module to v1.4.5
  Containerfile-alpine
  Containerfile-fedora
Labels: bug, patch

#82 Updates cloud-native-toolkit/image-cli-tools-core module to v1.4.6
  Containerfile-alpine
  Containerfile-fedora
Labels: bug, patch
